# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_Dzfjf-gdAJ5wWtkRC3b9K5NjRZ4YAA
"""

import pickle as pkl
import pandas as pd
with open("RandomForest.pkl", "rb") as f:
    object = pkl.load(f)

pkl.load(open("RandomForest.pkl","rb"))

